services:
  joomla:
    image: joomla:5-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/templates/bootstrap-italia-scuole
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: secret
      JOOMLA_DB_NAME: joomla
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - "PMA_HOST=db"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: secret
